name: pw6 autotests

on: 
  push:
    branches:
      - main
      
  workflow_dispatch:


jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.4.0
      - name: Устанавливаем пакеты из package.json
        run: npm ci
      - name: Install Allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://allure.autotests.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 5231
      - name: Устанавливаем браузеры
        run: npx playwright install --with-deps
      - name: Запускаем тесты с отправкой в TestOps
        run: allurectl watch -- npx playwright test
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          ALLURE_ENDPOINT: https://allure.autotests.cloud
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURE_PROJECT_ID: 5231
          ALLURE_RESULTS: allure-results
      - name: list
        run: ls
      - name: Генерирую отчет allure 3 в один файл
        run: npx allure awesome ./allure-results --single-file
        continue-on-error: true
        if: always()
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        continue-on-error: true
        if: always()
        with:
          name: artifacts
          path: |
            allure-report/index.html
            allure-results
            playwright-report
      - name: Отправка уведомления в Telegram
        uses: appleboy/telegram-action@master
        if: always()
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            🚀 *Сборка автотестов завершена!*
            
            *Проект:* pw6 autotests
            *Статус:* ${{ job.status == 'success' && '✅ Успешно' || '❌ Ошибка' }}
            
            🔗 [Открыть отчет Allure TestOps](https://allure.autotests.cloud/project/5231/launches/)
